*** Variables ***
${BROWSER}                      headlesschrome    # chrome, headlesschrome
${URL}                          https://talent-recruitment.test.bluestonepim.com/index.html
${EMAIL}                        admin@email.com
${PASSWORD}                     thisisverysecure
${WIDTH}                        1920
${HEIGHT}                       1080
${HEADLESS_THRESHOLD}           0.01
${NON_HEADLESS_THRESHOLD}       0.1
